Blef-team/blef_game_engine

- api/endpoints.R
- api/game_routines.R
- api/run_api.R
- api/run_api.sh
- appspec.yml
> Fix the api not starting on deployment

- api/endpoints.R
> Issue 8 add multiplayer related endpoints

- api/endpoints.R
- api/game_routines.R
- api/run_api.R
- api/run_api.sh
The first deployment attempt bumped at a "cleanup of previous deployment" issue.
Now, we deploy v1.0
> (Re)Deploy v1 of Game Engine Service

- .github/workflows/CI.yml
- api/run_api.R
> Deploy v1 of Game Engine Service

- .github/workflows/CI.yml
- deployment/codedeploy-deployment-policy.json
> Deplot Game Engine Service v1

- .github/workflows/CI.yml
Prevent double CI job triggered.
> Test updated CI behaviour

- api/game_routines.R
- api/indexation.csv
EDIT:
closes #36 , closes #37 
Now colours are ordered from 0-worst to 3-best.
> Change hand_type to set_type, reverse colour ordering and add action_id in indexation.csv

- api/endpoints.R
Closes #35, closes #38 .
It will be good for these two to be reviewed at the same time since the lines they change overlap.
> Change `requested_r` to `round` and coerce its type to `numeric`.

- api/endpoints.R
> Allow privacy changes only before game starts

- api/endpoints.R
- api/game_routines.R
> Fix games id returning 500 if player UUID provided and game not started

- api/endpoints.R
> Fix the get state endpoint, allowing for player UUID not to be provided

- api/endpoints.R
> Fix the game state endpoint not reporting hands for observers in the final round of the game

- api/README.md
- api/endpoints.R
> Prevent more than 8 players joining a game room

- api/endpoints.R
- api/game_routines.R
> Show players who lost in the 'players' array, but with n_cards equal to 0

- api/README.md
- api/endpoints.R
Closes #61 
EDIT: Also closes #43
> A big pull request refactoring and adding checks to 7 out of 8 endpoints

- api/endpoints.R
- api/game_routines.R
- api/run_api.sh
> Move game_data to home

- api/game_routines.R
> Fix key capitalisation in hands

- api/run_api.sh
> Add runtime logging to api service

- api/endpoints.R
> Fix the 500 error returned if player UUID is missing

- .github/workflows/CI.yml
- api/README.md
- api/endpoints.R
- api/game_routines.R
- api/run_api.R
- api/run_api.sh
- appspec.yml
> Issue 55 use separate base url for api version 2

- api/endpoints.R
> Return an empty array from the get public games endpoint if there are no games

- api/run_api.sh
- appspec.yml
> Run the app from opt/ instead of copying it into var

- api/run_api.sh
> Fix the relative paths in run_api.sh

- api/endpoints.R
> Remove the leading slash from games' UUID in the /games response

- .github/workflows/CI.yml
- api/README.md
- api/endpoints.R
- api/run_api.R
- api/run_api.sh
- appspec.yml
> Issue 105 prepare v3 paths

- api/game_routines.R
> Fix find_next_active_player

- .github/workflows/CI.yml
- api/README.md
- api/endpoints.R
- api/run_api.sh
- appspec.yml
> Rename v3 to v2.1

- .github/workflows/CI.yml
- api/README.md
- api/endpoints.R
- api/game_routines.R
- api/run_api.R
- api/run_api.sh
- appspec.yml
Minor deployment - fix a multiplayer game bug and fix the public game listing.
> Deploy v2.1

- api/endpoints.R
> Fix formatting of history at end of round

- .github/workflows/CI.yml
- api/README.md
- api/endpoints.R
- api/run_api.R
- api/run_api.sh
- appspec.yml
> Increment version to 2.2

- api/endpoints.R
> Nullify cp_nickname before saving snapshot

- api/endpoints.R
> If game is finished and last round queried, return snapshot before finish

- api/endpoints.R
> Do not convert admin_uuid to lower case before checking if it exists

- .github/workflows/CI.yml
- api/README.md
- api/endpoints.R
- api/game_routines.R
- api/run_api.R
- api/run_api.sh
- appspec.yml
> Deploy v2.2

- api/endpoints.R
> Consider present (not queried) game status when showing hands

- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
- api/run_api.R
- api/run_api.sh
- appspec.yml
- deployment/README.md
- deployment/validate_dev.sh
- deployment/validate_staging.sh
> Issue 132 create and modify ci to a develop staging prod workflow

- api/README.md
- api/endpoints.R
> Issue 131 create version endpoint

- api/README.md
- api/endpoints.R
> Issue 108 monitor the number of games and players

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/test_api.yml
- .github/workflows/test_api_prod.yml
- api/run_api.sh
- api/test/testing_utils.py
- appspec.yml
Requires: #129, #133, #134 
Closes #30
> Issue 30 automate integration testing

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
- api/test/run.sh
- api/test/tavern_tests/test_games.tavern.yaml
- api/test/testing_utils.py
> Issue 137 add test for version endpoint with a ci job

- README.md
> Add links to sub-project repos

- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/test_api.yml
- api/README.md
- api/endpoints.R
- api/run_api.sh
> Replace 2.2 with 2.3 across the repo

- api/run_api.sh
> Kill previous process at PORT before run_api.R

- deployment/validate_dev.sh
- deployment/validate_prod.sh
- deployment/validate_staging.sh
> Update validation scipts

- .github/workflows/test_api.yml
- appspec.yml
- deployment/clean_up.sh
> Add a cleanup step to deployment
